# Generated by Django 4.2.7 on 2023-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
