# Generated by Django 4.2.7 on 2023-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_by',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
